# "NodePort" type service to expose the api service to the outside world.
# web service(ClusterIP) <--- api service (NodePort) <--- crawler service (ClusterIP)
apiVersion: v1
kind: Service

metadata:
  name: crawler-service
  namespace: crawler
spec:
  selector:
    app: synergychat-crawler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080