# kubernetes service that load balances across different pods mentioned in selector/app
apiVersion: v1
kind: Service

metadata:
  name: web-service

spec:
  selector:
    app: synergychat-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080